language: ruby
dist: trusty
sudo: false
cache: bundler

branches:
  only: [master]

rvm:
  - 2.4.1

env:
  matrix:
    - "RAILS_MASTER=0"
    - "RAILS_MASTER=1"
before_install:
  - gem install bundler --no-document
  - bundle install
script:
  - RAILS_ENV=test bin/rake test
  - bin/rake rubocop:new
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database triage_test;' -U postgres
  - bin/rake db:migrate
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: SJwHN+BOodUbMjOGSIPRxqGnxQQ+20mC8pveALLYOmBp2SHtPKkYKX3AanqJ8jws2ZNnf1bg/RZER/PbbfKJ7q/9JiZ4FHBrIHQW8F0NI+tEoHummOag6Jc4A2tCaRWDPcl/B87NcmaDGjAfWuvAmD3MHL/trIdBhUfitmRNr9s=
  app: issuetriage
  on:
    repo: codetriage/codetriage
  run: "bin/rake db:migrate"
matrix:
  allow_failures:
    - env: "RAILS_MASTER=1"
