development:
  adapter: postgresql
  encoding: utf8
  database: triage_development
  pool: 5
  host: localhost
  # username: root


test:
  adapter: postgresql
  encoding: utf8
  database: triage_test
  pool: 5
  host: localhost
  username: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: triage_production
  pool: 5
  host: localhost
  # username: root
